import "bootstrap/dist/css/bootstrap.css"
import { Layout } from "@/components/Layout.js"
import Link from "next/link.js"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Layout>{ children }</Layout>
      </body>
    </html>
  )
}
